### ISSUE TITLE
Tutorial or More Complete Documentation

### ISSUE THREAD

**Issue by lee-orr** [LudiKha/Graphene#8]
Basically - as it stands right now, I wasn't able to decipher exactly what does what, and how to get a simple menu working from scratch. Even with the example, there are too many things that are unclear right now. Which is a shame - because it looks like this is something that tackles exactly the stuff I've been looking for.
So the request is for either a more complete documentation, or a step by step tutorial that covers all the basics of making a simple reactive UI (ideally, something that contains routing, parameters that can be changed, and maybe a list).

**Comment by LudiKha** [comment]
Hi @lee-orr ,

Thanks for the feedback - I agree that documentation still lacking! It's a fairly big task so I'm writing it step by step, and wanted to see if there's a demand at all first. That said, expect both expanded documentation and a more elaborate tutorial soon. I'll keep this open until more progress is made on documentation.

**Comment by lee-orr** [comment]
Looking forward to it!

**Comment by peterdijkstra** [comment]
Just popping in here to say that I am looking forward to a tutorial 😄 Graphene seems incredibly useful!

**Comment by lee-orr** [comment]
Any update on this? I'd really love to be able to give Graphene a more significant look, but don't currently know where to even start.

**Comment by LudiKha** [comment]
Hi @lee-orr , @peterdijkstra - apologies for disappearing there. Life & a product release got in the way. I'm still intending to update the documentation, and indeed further develop the package (I'm using it for my own production project). I will be sporadically available for the next couple of months, but will get to more updates hopefully after next month!

**Comment by lee-orr** [comment]
@LudiKha - thanks for the update! I was worried you'd decided to drop this. For my current (super rough) prototype I'm doing things manually, but I'd love to be able to use this & contribute once I start building a more complete version of my project.

**Comment by Fijo** [comment]
I'm gona start development on my own solution mainly because I'd like certain things to work with Observerables and UniRx Subjects as well as and more importantly be able to keep binding handlers seperated from controls as I want to keep it flexible so implementing new features won't be an issue going forward. I'm new to the whole unity thing since like summer 2020 so it won't be quite as fancy in the editor as yours but I have professional c# coding experience.

However I will keep an eye on this here and if it improves there's a good change I'll drop my solution and switch over or start using parts of your solution. Also I am open to talk about collaborations as we are doing very similar things. To make it clear though I know my time is limited and my focus is on my game but I know a good UI framwork will save time going forward so I will put some of my time into that if necessary.

To give you more of an idea as well I just want something close to knockoutjs for UI Toolkit. Angular is better ofc I just like to keep it simple.

I'm looking forward to seeing more people adopt UI Toolkit for runtime UI as well as watching projects like these take shape and being adopted.

**Comment by lee-orr** [comment]
@Fijo - I was thinking of doing a similar thing, however it's worth noting that UniRx hasn't been in development for over a year (last new commits were April 2019), which means if you run into issues, you'd need to patch them yourself.

**Comment by Fijo** [comment]
I'm aware of that. it is still a good framework though and there aren't any real alternatives. Something like that is an option ofc. https://ecsrx.gitbook.io/project/other/microrx

**Comment by Fijo** [comment]
Update: I have decided to wait a bit longer and before I get going with my own framwork and see what happens here and with other projects. Until then I'll keep the UI in my project simple ish and focus on other things.

> @LudiKha - thanks for the update! I was worried you'd decided to drop this. For my current (super rough) prototype I'm doing things manually, but I'd love to be able to use this & contribute once I start building a more complete version of my project.

As it stands now I completely agree with @lee-orr . Let's see what happens here.
