### ISSUE TITLE
The UI Toolkit Visual Debugger does not work

### ISSUE THREAD

**Issue by lee-orr** [LudiKha/Graphene#9]
In the visual debugger, when using Graphene, it just shows the root visual element. It would be useful, to help w/ theme design & fixing layout issues, if we could actually see the full hierarchy.

**Comment by LudiKha** [comment]
Graphene only builds the tree the when entering play mode, which is necessary (at least for the time being) because everything is composed dynamically. We could visualize things in edit-mode, but Graphene is primarily designed for runtime functionality, rather than a WYSIWYG workflow (which admittedly would be very useful to have)

If you're referring to 'Pick Element' not working properly - what versions are you on? I know that in previous versions of Unity/UI Toolkit this was an issue for me too when trying to pick element (See screenshot).

![image](https://user-images.githubusercontent.com/56917574/95775336-7f11e500-0cc2-11eb-809f-c2df4599abf6.png)

**Comment by lee-orr** [comment]
I'm currently on 2020.1.8, w/ UI Toolkit 1 preview 9 & UI Builder 1 preview 7 - and was referring to the "Pick Element"/hierarchy you're showing - during runtime. I'm not too concerned about edit mode at this point.
